latex_dictionary = {
	'density':'Density (\\autoref{eq:layer-1})',
	'density_re':'Density (\\autoref{eq:layer-1})',
	'density_full':'Density (\\autoref{eq:layer-loop}, T=3)',
	'density_half':'Density (\\autoref{eq:layer-2})',
	'density_stepped':'Density (\\autoref{eq:layer-loop}, T=1)',
	'mixture':'Mixture (\\autoref{eq:layer-1})',
	'mixture_re':'Mixture (\\autoref{eq:layer-1})',
	'mixture_full':'Mixture (\\autoref{eq:layer-loop}, T=3)',
	'mixture_half':'Mixture (\\autoref{eq:layer-2})',
	'mixture_stepped':'Mixture (\\autoref{eq:layer-loop}, T=1)',
	'mpiw':'$\\bar{w}$',
	'nmpiw':'$\\bar{w}_e$',
	'rmpiw':'$\\bar{w}_r$',
}

dictionary = {
	'density':'Density (Last Layer)',
	'density_re':'Density (Last Two Layers)',
	'density_full':'Density (Loop, T=3)',
	'density_half':'Density (Last Two Layers)',
	'density_stepped':'Density (Loop, T=1)',
	'mixture':'Mixture (Last Layer)',
	'mixture_re':'Mixture (Last Layer)',
	'mixture_full':'Mixture (Loop, T=3)',
	'mixture_half':'Mixture (Last Two Layers)',
	'mixture_stepped':'Mixture (Loop, T=1)',
	'mpiw':'Mean Interval Width',
	'nmpiw':'Mean Interval Width Divided by Error',
	'rmpiw':'Mean Interval Width Divided by Label Range',
	'ens-pairs':'Ensemble Pairs',
	'ensemble-pairs':'Ensemble Pairs (M=24)',
	'ensemble-pairs-3':'Ensemble Pairs (M=3)',
	'ensemble-pairs-6':'Ensemble Pairs (M=6)',
	'ensemble-pairs-12':'Ensemble Pairs (M=12)',
	'ensemble-pairs-balanced':'Ensemble Pairs (Balanced)',
	'ensemble-residuals':'Ensemble Residuals (M=24)',
	'ensemble-residuals-3':'Ensemble residuals (M=3)',
	'ensemble-residuals-6':'Ensemble residuals (M=6)',
	'ensemble-residuals-12':'Ensemble residuals (M=12)',
	'ensemble-residuals-balanced':'Ensemble Residuals (Balanced)',
	'ens-residuals':'Ensemble Residuals',
	'knn-mse':'kNN MSE',
	'knn-mseq':'kNN MSE (Quantiles)',
	'knn-vary':'kNN Label Var. (Quantiles)',
	'knn-dev':'kNN Deviation (Quantiles)',
	'knn-avgdist':'kNN AvgDist',
	'doho':'Dropout',
	'doho60':'Dropout (keep=0.6)',
	'doho70':'Dropout (keep=0.7)',
	'doho80':'Dropout (keep=0.8)',
	'doho90':'Dropout (keep=0.9)',
	'dohe60':'Dropout+Density (keep=0.6)',
	'dohe70':'Dropout+Density (keep=0.7)',
	'dohe80':'Dropout+Density (keep=0.8)',
	'dohe90':'Dropout+Density (keep=0.9)',
	'coverage':'Coverage',
	'ace':'ACE',
	'capi':'CAPI',
	'cec':'CEC',
	'cwc':'CWC',
	'cwc2':'CWC2',
	'cwc3':'CWC3',
	'pearson':'Pearson r',
	'pearson_p':'Pearson p-value',
	'winkler_score': 'Winkler',
	'f1':'F1',
	'precision':'Precision',
	'recall':'Recall',
	'mae': 'Mean Absolute Error',
	'rmse': 'Root Mean Square Error',
}

def translate(acronym, latex=True):
	if len(acronym) == 0 or acronym[0] == "\\": return acronym
	acronym = acronym.lower()
	if latex and acronym in latex_dictionary:
			return latex_dictionary[acronym]
	elif acronym in dictionary:
		return dictionary[acronym]
	return acronym.upper()
